name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Edu-2de
          outputs: |
            dist/github-contribution-grid-snake.svg
          color_snake: "#2aa889"
          color_dots: "#a8e6cf,#56c596,#2aa889,#218c5f,#145c37"

      - uses: actions/upload-artifact@v3
        with:
          name: snake-graphic
          path: dist/github-contribution-grid-snake.svg

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
