name: Generate snake animation (Gotham Green)

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg (Gotham Green palette, dark dots, glow effect)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?palette=[0C1015,1de160,232B33,232B33]&effect=glow
            # 0C1015 = fundo Gotham
            # 1de160 = verde neon para a cobra
            # 232B33 = quadrados/dots escuros
            # 232B33 = apple (comida) escuro também
            # effect=glow = efeito de brilho só na cobra

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
